config/routes.rb
Rails.application.routes.draw do
  root "pages#home" #get 'pages/home'
  get 'about', to: 'pages#about'
  resources :events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  
  validates :Name_of_Event, presence: true, length: { maximum: 30 }
  validates :Country, presence: true, length: { minimum: 2, maximum: 30 }
  validates :Description, presence: true, length: { minimum: 5, maximum: 1000 }
  validates :Distance_participating, presence: true
  validates :Date_of_Event, presence: true, numericality: { only_integer: true }, length: { is: 8 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
   @event = Event.new(params.require(:event).permit(:Name_of_Event, :Distance_participating, :Country, :Date_of_Event, :Description)) 
    if @event.save
        flash[:notice] = "Event was successfully submitted"
        redirect_to @event
     else
       render 'new'
     end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/index.html.erb
<h1>This is the Index Page </h1>
<table>
  <thead>
    <tr>
      <th>Name of Event |</th>
      <th>Country |</th>
      <th>Distance Participating |</th>
      <th>Date of Event |</th>
      <th>Description |</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.Name_of_Event %></td>
        <td><%= event.Country %></td>
        <td><%= event.Distance_participating %></td>
        <td><%= event.Date_of_Event %></td>
        <td><%= event.Description %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/events/new.html.erb
<h1> You can submit Events on this page</h1>

<% if @event.errors.any? %>
  <h2>The following errors prevented the Event from being submitted</h2>
    <ul>
      <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

<%= form_with scope: :event, url: events_path, local: true do |f| %>
  <p>
    <%= f.label :Name_of_Event %></br> 
    <%= f.text_field :Name_of_Event %></br>
  </p>
  <p>
    <%= f.label :Date_of_Event_DDMMYYYY %></br> 
    <%= f.text_field :Date_of_Event %></br>
  </p>
  <p>
    <%= f.label :Participating_distance %></br> 
    <%= f.text_field :Distance_participating %></br>
  </p>
  <p>
    <%= f.label :Country %></br> 
    <%= f.text_area :Country %></br>
  </p>
    <p>
    <%= f.label :Description %></br> 
    <%= f.text_area :Description %></br>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/events/show.html.erb
<h1>This page shows the details of a specific event </h1>

<p><strong>Event Name: </strong><%= @event.Name_of_Event %></p>
<p><strong>Distance: </strong><%= @event.Distance_participating %></p>
<p><strong>Country: </strong><%= @event.Country %></p>
<p><strong>Date of Event: </strong><%= @event.Date_of_Event %></p>
<p><strong>Description: </strong><%= @event.Description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adventure Events</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
    <%= msg %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the Abouts page</h1>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>